GET http://localhost:8000/tasks/

###

GET http://localhost:8000/tasks/01JSPC0SNDTGW0XP7CZEWJZKEN

###

POST http://localhost:8000/tasks/
Content-Type: application/json

{
	"title": "Task title",
	"content": "Task content",
	"completed": false,
    "creator": "01JSP9J68CK06JQMHQY04QS3MG",
	"date": {
		"created": 1673213200,
		"completed": 1673213200,
		"expected": 1673213200
	},
	"categories": ["category1", "category2"],
	"priority": 1
}