GET http://localhost:8000/tasks/

###

POST http://localhost:8000/tasks/
Content-Type: application/json

{
	"title": "Task title",
	"content": "Task content",
	"completed": false,
    "creator": "",
	"date": {
		"created": 1673213200,
		"completed": 1673213200,
		"expected": 1673213200
	},
	"categories": ["category1", "category2"],
	"priority": 1
}