###
GET http://localhost:8000/users/01JTRRQPE7AAHAV239AX113N0F

### 
POST http://localhost:8000/users/
Content-Type: application/json

{
	"name": "Messi",
    "email": "messi@gmail.com",
    "password": "password",
    "avatar": "https://img.a.transfermarkt.technology/portrait/header/28003-1740766555.jpg?lm=1"
}

### 

PATCH http://localhost:8000/users/01JSPBGVGKDBDF17WP763TXW72


###

DELETE http://localhost:8000/users/01JSPBGVGKDBDF17WP763TXW72