###
GET http://localhost:8000/users/01JSN2M5RANS5JZ7ARJK5H1CB3

### 
POST http://localhost:8000/users/
Content-Type: application/json

{
	"name": "Pablito",
    "email": "pablito2@gmail.com",
    "password": "password",
    "avatar": "https://url.com/avatar.png"
}

### 

PATCH http://localhost:8000/users/


###

DELETE http://localhost:8000/users/01JSN2M5RANS5JZ7ARJK5H1CB3