###
GET http://localhost:8000/users/01JV6ZJPKPT56V4R34J0NSGY04

### 
POST http://localhost:8000/users/
Content-Type: application/json

{
	"name": "Vegeta",
    "email": "Vegeta@gmail.com",
    "password": "password",
    "avatar": "https://fwmedia.fandomwire.com/wp-content/uploads/2025/03/05060705/Dragonball-Z-Vegeta.jpg"
}

### 

PATCH http://localhost:8000/users/01JSPBGVGKDBDF17WP763TXW72


###

DELETE http://localhost:8000/users/01JSPBGVGKDBDF17WP763TXW72